### ISSUE TITLE
GameController.maze is inaccessible due to its protection level

### ISSUE THREAD

**Issue by FrankM97** [Bloomfield-SP20-CAT328/AMazingGame-FrankMarinelli#2]
Its probably something I'm leaving out, But I can't figure out what it is. Once this is fixed. the REDO COMMIT FOR ASSIGNMENT 14 should work as intended.

**Comment by ProfPollati** [comment]
Think about if it's `public`, `protected` or `private`...

**Comment by ProfPollati** [comment]
https://github.com/Bloomfield-SP20-CAT328/AMazingGame-FrankMarinelli/blob/11b8d3c1f0a95b58d3f14874bc006995f6eddc7b/Assignment%20AMazingGame/Assets/Scripts/GameController.cs#L20

Since there is no protection defined, C# will make it `private` and you won't be able to access it.

**Comment by FrankM97** [comment]
Forgot to close this. Fixed!
